### ISSUE TITLE
Deadlink: platform-specific Julia installation

### ISSUE THREAD

**Issue by timduff35** [JuliaHomotopyContinuation/juliahomotopycontinuation.github.io#20]
Accessing [platform specific instructions](https://julialang.org/downloads/platform.html) from the [installation page](https://www.juliahomotopycontinuation.org/guides/installation/) no longer works. It looks like the new url is https://www.julialang.org/downloads/platform/.

**Comment by saschatimme** [comment]
Thanks Tim!
